name: Deploy Google Function to gcloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy FPL League Ranking
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: fpl-league-ranking
          runtime: nodejs16
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }
          source_dir: src
          entry_point: leagueRanking
          memory_mb: 128MB
          max_instances: 1
          region: europe-west2
          env_vars:
            - SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}
