name: Deploy Google Function to gcloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build & Test
        run: |
          npm install
          npm test

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Deploy FPL League Ranking
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: fpl-league-ranking
          runtime: $runtime
          source_dir: $source_dir
          entry_point: leagueRanking
          memory_mb: $memory_mb
          max_instances: $max_instances
          region: $region
          env_vars: $env_vars

      - name: Deploy FPL Player History
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: fpl-player-history
          runtime: $runtime
          source_dir: $source_dir
          entry_point: playerHistory
          memory_mb: $memory_mb
          max_instances: $max_instances
          region: $region
          env_vars: $env_vars

    - env:
        runtime: 128
        source_dir: src
        memory_mb: 128
        max_instances: 1
        region: europe-west2
        env_vars: SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}
